import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();
async function main() {
  await prisma.tshirt.deleteMany({});

  const tshirts = [
    {
      title: 'Tshirt Amadou',
      price: 35,
      color: 'GREEN',
      size: 'S',
      description: 'Tshirt Amadou Balake Green',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Amadou',
      price: 35,
      color: 'GREEN',
      size: 'M',
      description: 'Tshirt Amadou Balake Green',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Amadou',
      price: 35,
      color: 'GREEN',
      size: 'L',
      description: 'Tshirt Amadou Balake Green',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Amadou',
      price: 35,
      color: 'GREEN',
      size: 'XL',
      description: 'Tshirt Amadou Balake Green',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Amadou',
      price: 35,
      color: 'RED',
      size: 'S',
      description: 'Tshirt Amadou Balake Red',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Amadou',
      price: 35,
      color: 'RED',
      size: 'M',
      description: 'Tshirt Amadou Balake Red',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Amadou',
      price: 35,
      color: 'RED',
      size: 'L',
      description: 'Tshirt Amadou Balake Red',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Amadou',
      price: 35,
      color: 'RED',
      size: 'XL',
      description: 'Tshirt Amadou Balake Red',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Amadou',
      price: 35,
      color: 'BLACK',
      size: 'S',
      description: 'Tshirt Amadou Balake Black',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Amadou',
      price: 35,
      color: 'BLACK',
      size: 'M',
      description: 'Tshirt Amadou Balake Black',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Amadou',
      price: 35,
      color: 'BLACK',
      size: 'L',
      description: 'Tshirt Amadou Balake Black',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Amadou',
      price: 35,
      color: 'BLACK',
      size: 'XL',
      description: 'Tshirt Amadou Balake Black',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Amadou',
      price: 35,
      color: 'PURPLE',
      size: 'S',
      description: 'Tshirt Amadou Balake Purple',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Amadou',
      price: 35,
      color: 'PURPLE',
      size: 'M',
      description: 'Tshirt Amadou Balake Purple',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Amadou',
      price: 35,
      color: 'PURPLE',
      size: 'L',
      description: 'Tshirt Amadou Balake Purple',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Amadou',
      price: 35,
      color: 'PURPLE',
      size: 'XL',
      description: 'Tshirt Amadou Balake Purple',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Amadou',
      price: 35,
      color: 'YELLOW',
      size: 'S',
      description: 'Tshirt Amadou Balake Yellow',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Amadou',
      price: 35,
      color: 'YELLOW',
      size: 'M',
      description: 'Tshirt Amadou Balake Yellow',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Amadou',
      price: 35,
      color: 'YELLOW',
      size: 'L',
      description: 'Tshirt Amadou Balake Yellow',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Amadou',
      price: 35,
      color: 'YELLOW',
      size: 'XL',
      description: 'Tshirt Amadou Balake Yellow',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Dao',
      price: 35,
      color: 'GREEN',
      size: 'S',
      description: 'Tshirt Dao Green',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Dao',
      price: 35,
      color: 'GREEN',
      size: 'M',
      description: 'Tshirt Dao Green',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Dao',
      price: 35,
      color: 'GREEN',
      size: 'L',
      description: 'Tshirt Dao Green',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Dao',
      price: 35,
      color: 'GREEN',
      size: 'XL',
      description: 'Tshirt Dao Green',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Dao',
      price: 35,
      color: 'RED',
      size: 'S',
      description: 'Tshirt Dao Red',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Dao',
      price: 35,
      color: 'RED',
      size: 'M',
      description: 'Tshirt Dao Red',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Dao',
      price: 35,
      color: 'RED',
      size: 'L',
      description: 'Tshirt Dao Red',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Dao',
      price: 35,
      color: 'RED',
      size: 'XL',
      description: 'Tshirt Dao Red',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Dao',
      price: 35,
      color: 'BLACK',
      size: 'S',
      description: 'Tshirt Dao Black',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Dao',
      price: 35,
      color: 'BLACK',
      size: 'M',
      description: 'Tshirt Dao Black',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Dao',
      price: 35,
      color: 'BLACK',
      size: 'L',
      description: 'Tshirt Dao Black',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Dao',
      price: 35,
      color: 'BLACK',
      size: 'XL',
      description: 'Tshirt Dao Black',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Dao',
      price: 35,
      color: 'PURPLE',
      size: 'S',
      description: 'Tshirt Dao Purple',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Dao',
      price: 35,
      color: 'PURPLE',
      size: 'M',
      description: 'Tshirt Dao Purple',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Dao',
      price: 35,
      color: 'PURPLE',
      size: 'L',
      description: 'Tshirt Dao Purple',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Dao',
      price: 35,
      color: 'PURPLE',
      size: 'XL',
      description: 'Tshirt Dao Purple',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Dao',
      price: 35,
      color: 'YELLOW',
      size: 'S',
      description: 'Tshirt Dao Yellow',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Dao',
      price: 35,
      color: 'YELLOW',
      size: 'M',
      description: 'Tshirt Dao Yellow',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Dao',
      price: 35,
      color: 'YELLOW',
      size: 'L',
      description: 'Tshirt Dao Yellow',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Dao',
      price: 35,
      color: 'YELLOW',
      size: 'XL',
      description: 'Tshirt Dao Yellow',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Electric',
      price: 35,
      color: 'GREEN',
      size: 'S',
      description: 'Tshirt Electric Prunes Green',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Electric',
      price: 35,
      color: 'GREEN',
      size: 'M',
      description: 'Tshirt Electric Prunes Green',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Electric',
      price: 35,
      color: 'GREEN',
      size: 'L',
      description: 'Tshirt Electric Prunes Green',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Electric',
      price: 35,
      color: 'GREEN',
      size: 'XL',
      description: 'Tshirt Electric Prunes Green',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Electric',
      price: 35,
      color: 'RED',
      size: 'S',
      description: 'Tshirt Electric Prunes Red',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Electric',
      price: 35,
      color: 'RED',
      size: 'M',
      description: 'Tshirt Electric Prunes Red',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Electric',
      price: 35,
      color: 'RED',
      size: 'L',
      description: 'Tshirt Electric Prunes Red',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Electric',
      price: 35,
      color: 'RED',
      size: 'XL',
      description: 'Tshirt Electric Prunes Red',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Electric',
      price: 35,
      color: 'BLACK',
      size: 'S',
      description: 'Tshirt Electric Prunes Black',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Electric',
      price: 35,
      color: 'BLACK',
      size: 'M',
      description: 'Tshirt Electric Prunes Black',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Electric',
      price: 35,
      color: 'BLACK',
      size: 'L',
      description: 'Tshirt Electric Prunes Black',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Electric',
      price: 35,
      color: 'BLACK',
      size: 'XL',
      description: 'Tshirt Electric Prunes Black',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Electric',
      price: 35,
      color: 'PURPLE',
      size: 'S',
      description: 'Tshirt Electric Prunes Purple',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Electric',
      price: 35,
      color: 'PURPLE',
      size: 'M',
      description: 'Tshirt Electric Prunes Purple',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Electric',
      price: 35,
      color: 'PURPLE',
      size: 'L',
      description: 'Tshirt Electric Prunes Purple',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Electric',
      price: 35,
      color: 'PURPLE',
      size: 'XL',
      description: 'Tshirt Electric Prunes Purple',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Electric',
      price: 35,
      color: 'YELLOW',
      size: 'S',
      description: 'Tshirt Electric Prunes Yellow',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Electric',
      price: 35,
      color: 'YELLOW',
      size: 'M',
      description: 'Tshirt Electric Prunes Yellow',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Electric',
      price: 35,
      color: 'YELLOW',
      size: 'L',
      description: 'Tshirt Electric Prunes Yellow',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Electric',
      price: 35,
      color: 'YELLOW',
      size: 'XL',
      description: 'Tshirt Electric Prunes Yellow',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Maalem',
      price: 35,
      color: 'GREEN',
      size: 'S',
      description: 'Tshirt Maalem Mahmoud Gania Green',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Maalem',
      price: 35,
      color: 'GREEN',
      size: 'M',
      description: 'Tshirt Maalem Mahmoud Gania Green',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Maalem',
      price: 35,
      color: 'GREEN',
      size: 'L',
      description: 'Tshirt Maalem Mahmoud Gania Green',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Maalem',
      price: 35,
      color: 'GREEN',
      size: 'XL',
      description: 'Tshirt Maalem Mahmoud Gania Green',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Maalem',
      price: 35,
      color: 'RED',
      size: 'S',
      description: 'Tshirt Maalem Mahmoud Gania Red',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Maalem',
      price: 35,
      color: 'RED',
      size: 'M',
      description: 'Tshirt Maalem Mahmoud Gania Red',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Maalem',
      price: 35,
      color: 'RED',
      size: 'L',
      description: 'Tshirt Maalem Mahmoud Gania Red',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Maalem',
      price: 35,
      color: 'RED',
      size: 'XL',
      description: 'Tshirt Maalem Mahmoud Gania Red',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Maalem',
      price: 35,
      color: 'BLACK',
      size: 'S',
      description: 'Tshirt Maalem Mahmoud Gania Black',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Maalem',
      price: 35,
      color: 'BLACK',
      size: 'M',
      description: 'Tshirt Maalem Mahmoud Gania Black',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Maalem',
      price: 35,
      color: 'BLACK',
      size: 'L',
      description: 'Tshirt Maalem Mahmoud Gania Black',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Maalem',
      price: 35,
      color: 'BLACK',
      size: 'XL',
      description: 'Tshirt Maalem Mahmoud Gania Black',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Maalem',
      price: 35,
      color: 'PURPLE',
      size: 'S',
      description: 'Tshirt Maalem Mahmoud Gania Purple',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Maalem',
      price: 35,
      color: 'PURPLE',
      size: 'M',
      description: 'Tshirt Maalem Mahmoud Gania Purple',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Maalem',
      price: 35,
      color: 'PURPLE',
      size: 'L',
      description: 'Tshirt Maalem Mahmoud Gania Purple',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Maalem',
      price: 35,
      color: 'PURPLE',
      size: 'XL',
      description: 'Tshirt Maalem Mahmoud Gania Purple',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Maalem',
      price: 35,
      color: 'YELLOW',
      size: 'S',
      description: 'Tshirt Maalem Mahmoud Gania Yellow',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Maalem',
      price: 35,
      color: 'YELLOW',
      size: 'M',
      description: 'Tshirt Maalem Mahmoud Gania Yellow',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Maalem',
      price: 35,
      color: 'YELLOW',
      size: 'L',
      description: 'Tshirt Maalem Mahmoud Gania Yellow',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Maalem',
      price: 35,
      color: 'YELLOW',
      size: 'XL',
      description: 'Tshirt Maalem Mahmoud Gania Yellow',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Maalem',
      price: 35,
      color: 'WHITE',
      size: 'S',
      description: 'Tshirt Maalem Mahmoud Gania White',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Maalem',
      price: 35,
      color: 'WHITE',
      size: 'M',
      description: 'Tshirt Maalem Mahmoud Gania White',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Maalem',
      price: 35,
      color: 'WHITE',
      size: 'L',
      description: 'Tshirt Maalem Mahmoud Gania White',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Maalem',
      price: 35,
      color: 'WHITE',
      size: 'XL',
      description: 'Tshirt Maalem Mahmoud Gania White',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Dao',
      price: 35,
      color: 'WHITE',
      size: 'S',
      description: 'Tshirt Dao White',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Dao',
      price: 35,
      color: 'WHITE',
      size: 'M',
      description: 'Tshirt Dao White',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Dao',
      price: 35,
      color: 'WHITE',
      size: 'L',
      description: 'Tshirt Dao White',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Dao',
      price: 35,
      color: 'WHITE',
      size: 'XL',
      description: 'Tshirt Dao White',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Electric',
      price: 35,
      color: 'WHITE',
      size: 'S',
      description: 'Tshirt Electric Prunes White',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Electric',
      price: 35,
      color: 'WHITE',
      size: 'M',
      description: 'Tshirt Electric Prunes White',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Electric',
      price: 35,
      color: 'WHITE',
      size: 'L',
      description: 'Tshirt Electric Prunes White',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Electric',
      price: 35,
      color: 'WHITE',
      size: 'XL',
      description: 'Tshirt Electric Prunes White',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Electric',
      price: 35,
      color: 'WHITE',
      size: 'S',
      description: 'Tshirt Electric Prunes White',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Amadou',
      price: 35,
      color: 'WHITE',
      size: 'M',
      description: 'Tshirt Amadou Balake White',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Amadou',
      price: 35,
      color: 'WHITE',
      size: 'L',
      description: 'Tshirt Amadou Balake White',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
    {
      title: 'Tshirt Amadou',
      price: 35,
      color: 'WHITE',
      size: 'XL',
      description: 'Tshirt Amadou Balake White',
      imageUrl: '',
      providerId: 1,
      stock: 5,
    },
  ];

  prisma.tshirt.createMany({
    data: tshirts,
  });
}

main()
  .catch(() => {
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
